server:
  port: 8082
spring:
  application:
    name: catalog-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5439/academy}
    username: ${DATABASE_USER:academy}
    password: ${DATABASE_PASSWORD:academy}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: catalog
  flyway:
    schemas: catalog
    default-schema: catalog
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
